# Generated by Django 4.1.5 on 2023-01-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории развлечений',
            },
        ),
        migrations.CreateModel(
            name='Category_hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории размещений',
            },
        ),
        migrations.CreateModel(
            name='Category_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории заведений',
            },
        ),
        migrations.CreateModel(
            name='SubCategory_place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.ManyToManyField(blank=True, to='main.category_place')),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухня',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('food', 'ЕДА'), ('fun', 'РАЗВЛЕЧЕНИЯ'), ('hotel', 'РАЗМЕЩЕНИЕ')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('hours', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='place')),
                ('map_link', models.CharField(blank=True, max_length=255)),
                ('place_link', models.CharField(blank=True, max_length=255)),
                ('avg_price', models.CharField(blank=True, max_length=255)),
                ('category', models.ManyToManyField(related_name='category_place', to='main.category_place')),
                ('sub_category', models.ManyToManyField(related_name='subcategory_place', to='main.subcategory_place')),
            ],
            options={
                'verbose_name': 'Еда',
                'verbose_name_plural': 'Еда',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('food', 'ЕДА'), ('fun', 'РАЗВЛЕЧЕНИЯ'), ('hotel', 'РАЗМЕЩЕНИЕ')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('hours', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='hotel')),
                ('map_link', models.CharField(blank=True, max_length=255)),
                ('hotel_link', models.CharField(blank=True, max_length=255)),
                ('price', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_hotel', to='main.category_hotel')),
            ],
            options={
                'verbose_name': 'Размещение',
                'verbose_name_plural': 'Размещение',
            },
        ),
        migrations.CreateModel(
            name='Fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('food', 'ЕДА'), ('fun', 'РАЗВЛЕЧЕНИЯ'), ('hotel', 'РАЗМЕЩЕНИЕ')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('hours', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='fun')),
                ('map_link', models.CharField(blank=True, max_length=255)),
                ('fun_link', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_fun', to='main.category_fun')),
            ],
            options={
                'verbose_name': 'Развлечение',
                'verbose_name_plural': 'Развлечения',
            },
        ),
    ]
