# Generated by Django 4.1.5 on 2023-01-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_fun',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории развлечений'},
        ),
        migrations.AlterModelOptions(
            name='category_hotel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории размещений'},
        ),
        migrations.AlterModelOptions(
            name='category_place',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории заведений'},
        ),
    ]
