# Generated by Django 4.1.5 on 2023-01-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_category_fun_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_place',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
