# Generated by Django 4.1.5 on 2023-01-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_place_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fun',
            name='image',
            field=models.ImageField(blank=True, upload_to='fun'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, upload_to='place'),
        ),
    ]
