# Generated by Django 4.1.5 on 2023-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_place_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fun',
            options={'verbose_name': 'Развлечение', 'verbose_name_plural': 'Развлечения'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'Размещение', 'verbose_name_plural': 'Размещение'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Еда', 'verbose_name_plural': 'Еда'},
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='fun',
            name='image',
            field=models.ImageField(blank=True, upload_to='fun'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, upload_to='hotel'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, upload_to='place'),
        ),
    ]
