# Generated by Django 4.1.5 on 2023-01-18 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_fun_image_alter_hotel_image_alter_place_image'),
        ('main', '0004_alter_fun_options_alter_hotel_options_and_more'),
    ]

    operations = [
    ]
