# Generated by Django 4.1.5 on 2023-01-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_fun_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fun',
            name='fun_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='avg_price',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='place_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
