# Generated by Django 4.1.5 on 2023-01-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_fun_fun_link_place_avg_price_place_place_link'),
        ('main', '0005_merge_20230118_0626'),
    ]

    operations = [
    ]
