# Generated by Django 4.1.5 on 2023-01-22 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelcommentlike',
            name='user_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FunCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fun_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun_likes', to='review.funcomment')),
                ('user_fun_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fun_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
