# Generated by Django 4.1.5 on 2023-01-22 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0002_alter_hotelcommentlike_user_comment_funcommentlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_likes', to='review.placecomment')),
                ('user_place_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
